### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'keywords')

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#98]
I receive this error while editing some members

```Error parsing /wfisrc/qrpgsrc/prp03c.rpgle: Cannot read properties of undefined (reading 'keywords')
TypeError: Cannot read properties of undefined (reading 'keywords')
	at e.exports.getDocs (c:\Users\USER\.vscode\extensions\halcyontechltd.vscode-rpgle-0.7.2\dist\extension.js:1:35328)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.provideDocumentSymbols (c:\Users\USER\.vscode\extensions\halcyontechltd.vscode-rpgle-0.7.2\dist\extension.js:1:43951)
	at async o.provideDocumentSymbols (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:129081)
```
followed by 
```
Error parsing /wfisrc/qrpgsrc/prp03c.rpgle: Cannot read properties of undefined (reading 'keywords')
TypeError: Cannot read properties of undefined (reading 'keywords')
	at e.exports.getDocs (c:\Users\USER\.vscode\extensions\halcyontechltd.vscode-rpgle-0.7.2\dist\extension.js:1:35328)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.provideDocumentSymbols (c:\Users\USER\.vscode\extensions\halcyontechltd.vscode-rpgle-0.7.2\dist\extension.js:1:43951)
	at async o.provideDocumentSymbols (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:129081)
```

Program is a **FREE source member at 4871 lines of code.

The outline and other features seem to be disabled while I see these error.

**Comment by worksofliam** [comment]
@m-tyler There are really two ways to solve this:

* Share some source with me privately with me so I can recreate it
* Recreate the issue in a small file

**Comment by worksofliam** [comment]
@m-tyler Sounds like the issue could be in one of the copybooks from the base library you copied from then. Let me know if you eventually recreate the issue! I'd love to tackle this.

**Comment by m-tyler** [comment]
I am not certain that is it.  I only copied the main program source into my developer temp member.   I currently have NO members in my developer /COPY source file.  We use only one source file, QCPYSRC, for /COPY members.

> I have to correct my original statement.  I thought this issue was from a **FREE source version because that is the source I was working with when I noticed the issue.  However, in my attempt to recreate the problem and discovered which source is causing the error.   I should have noticed which source caused the error because in the second image in the first post, sorry for the misleading information.

The source that causes the error (same program just the production version) is a mix of fixed and free-format RPGLE which has free-form internal procedures.   This is the same program source I copied into my developer temp member, I talked about above which does not cause the error. 

We have four source environments, developer, integration, quality, and production.  The error only appears with this source n the production environment.  I have put the source into the other environments and opened the source and the error does not appear. 

Is there a setting (in my current installation) I can add to make the logging be more verbose?  Maybe so it can report the source part that is causing the error?

**Comment by worksofliam** [comment]
There isn't more verbose logging (yet). That is something that could be looked into, though.

**Comment by m-tyler** [comment]
So I am now able to recreate the issue in my developer environment.  I copied all the /COPY members into my environment and opened the temp member source of the production version.  I get the same errors.  I am going to one by one rename the /COPY members to see if I can find the one causing the issue.

**Comment by m-tyler** [comment]
Okay, I think I have recreated the issue.

This /COPY member causes errors to appear when opened. 
[F4DATE.RPGLE.txt](https://github.com/halcyon-tech/vscode-rpgle/files/9074595/F4DATE.RPGLE.txt)

When included in a source member it gives the reported error.  I only need to include this member in a temp source file for the reported error to appear.

Error when /COPY member opened.
```
Error parsing /WIASP/USER/QCPYSRC/F4DATE.RPGLE: Cannot read properties of undefined (reading 'keywords')
TypeError: Cannot read properties of undefined (reading 'keywords')
	at e.exports.getDocs (c:\Users\USER\.vscode\extensions\halcyontechltd.vscode-rpgle-0.7.2\dist\extension.js:1:35328)
	at Object.provideDocumentSymbols (c:\Users\USER\.vscode\extensions\halcyontechltd.vscode-rpgle-0.7.2\dist\extension.js:1:43959)
	at o.provideDocumentSymbols (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:129102)
	at c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:159280
	at te._withAdapter (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:158424)
	at te.$provideDocumentSymbols (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:159258)
	at s._doInvokeHandler (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\
api\node\extensionHostProcess.js:86:13828)
	at s._invokeHandler (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13512)
	at s._receiveRequest (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:12121)
	at s._receiveOneMessage (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:10843)
	at c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:8949
	at g.invoke (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at a.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19025)
	at c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:34863
	at g.invoke (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at a.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19025)
	at r._receiveMessage (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23606)
	at c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21140
	at g.invoke (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at v.acceptChunk (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15856)
	at c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14986
	at Socket.R (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13798)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by worksofliam** [comment]
@m-tyler Great work on tracking it down. I have been able to get the same error.

**Comment by worksofliam** [comment]
0.7.3 coming out now with a fix. Test case was also created for this issue.
